USER_ROLE_ADMIN = "admin"
USER_ROLE_EDITOR = "editor"
USER_ROLE_VIEWER = "viewer"

ALLOWED_USER_ROLES = {
    USER_ROLE_ADMIN,
    USER_ROLE_EDITOR,
    USER_ROLE_VIEWER,
}

LICENSE_STATUS_NEW = "new"
LICENSE_STATUS_ACTIVATED = "activated"
LICENSE_STATUS_EXPIRED = "expired"
LICENSE_STATUS_BLOCKED = "blocked"

ALLOWED_LICENSE_STATUSES = {
    LICENSE_STATUS_NEW,
    LICENSE_STATUS_ACTIVATED,
    LICENSE_STATUS_EXPIRED,
    LICENSE_STATUS_BLOCKED,
}


ASSET_TYPE_COMPUTER = "computer"
ASSET_TYPE_LAPTOP = "laptop"
ASSET_TYPE_MONITOR = "monitor"
ASSET_TYPE_PRINTER = "printer"
ASSET_TYPE_MFU = "mfu"
ASSET_TYPE_PROJECTOR = "projector"
ASSET_TYPE_INTERACTIVE_BOARD = "interactive_board"
ASSET_TYPE_TABLET = "tablet"
ASSET_TYPE_SERVER = "server"
ASSET_TYPE_NETWORK_DEVICE = "network_device"
ASSET_TYPE_UPS = "ups"
ASSET_TYPE_OTHER = "other"

ALLOWED_ASSET_TYPES = {
    ASSET_TYPE_COMPUTER,
    ASSET_TYPE_LAPTOP,
    ASSET_TYPE_MONITOR,
    ASSET_TYPE_PRINTER,
    ASSET_TYPE_MFU,
    ASSET_TYPE_PROJECTOR,
    ASSET_TYPE_INTERACTIVE_BOARD,
    ASSET_TYPE_TABLET,
    ASSET_TYPE_SERVER,
    ASSET_TYPE_NETWORK_DEVICE,
    ASSET_TYPE_UPS,
    ASSET_TYPE_OTHER,
}


ASSET_STATUS_IN_USE = "in_use"
ASSET_STATUS_IN_STORAGE = "in_storage"
ASSET_STATUS_IN_REPAIR = "in_repair"
ASSET_STATUS_NEEDS_REPAIR = "needs_repair"
ASSET_STATUS_WRITTEN_OFF = "written_off"
ASSET_STATUS_LOST = "lost"

ALLOWED_ASSET_STATUSES = {
    ASSET_STATUS_IN_USE,
    ASSET_STATUS_IN_STORAGE,
    ASSET_STATUS_IN_REPAIR,
    ASSET_STATUS_NEEDS_REPAIR,
    ASSET_STATUS_WRITTEN_OFF,
    ASSET_STATUS_LOST,
}


USER_CATEGORY_TEACHER = "teacher"
USER_CATEGORY_STUDENT = "student"
USER_CATEGORY_ADMINISTRATION = "administration"
USER_CATEGORY_IT_STAFF = "it_staff"
USER_CATEGORY_SHARED = "shared"
USER_CATEGORY_OTHER = "other"

ALLOWED_USER_CATEGORIES = {
    USER_CATEGORY_TEACHER,
    USER_CATEGORY_STUDENT,
    USER_CATEGORY_ADMINISTRATION,
    USER_CATEGORY_IT_STAFF,
    USER_CATEGORY_SHARED,
    USER_CATEGORY_OTHER,
}

HISTORY_EVENT_CREATED = "created"
HISTORY_EVENT_UPDATED = "updated"
HISTORY_EVENT_STATUS_CHANGED = "status_changed"
HISTORY_EVENT_ROOM_CHANGED = "room_changed"
HISTORY_EVENT_RESPONSIBLE_CHANGED = "responsible_changed"
HISTORY_EVENT_USER_CATEGORY_CHANGED = "user_category_changed"
HISTORY_EVENT_OS_CHANGED = "os_changed"
HISTORY_EVENT_DESCRIPTION_CHANGED = "description_changed"
HISTORY_EVENT_MANUAL_NOTE = "manual_note"
HISTORY_EVENT_DELETED = "deleted"
HISTORY_EVENT_RESTORED = "restored"


TRACKED_ASSET_HISTORY_FIELDS = {
    "status": HISTORY_EVENT_STATUS_CHANGED,
    "room": HISTORY_EVENT_ROOM_CHANGED,
    "responsible_person": HISTORY_EVENT_RESPONSIBLE_CHANGED,
    "user_category": HISTORY_EVENT_USER_CATEGORY_CHANGED,
    "os": HISTORY_EVENT_OS_CHANGED,
    "description": HISTORY_EVENT_DESCRIPTION_CHANGED,
}

# Категории техники для статистического отчёта ОО-2, раздел 2.1.
# Они отделены от обычного поля Asset.type, потому что один и тот же
# пользовательский тип техники в будущем может попадать в разные отчёты по-разному.
REPORT_CATEGORY_DESKTOP_PC = "desktop_pc"
REPORT_CATEGORY_LAPTOP = "laptop"
REPORT_CATEGORY_TABLET = "tablet"
REPORT_CATEGORY_TERMINAL = "terminal"
REPORT_CATEGORY_INFO_TERMINAL = "info_terminal"
REPORT_CATEGORY_PROJECTOR = "projector"
REPORT_CATEGORY_INTERACTIVE_BOARD = "interactive_board"
REPORT_CATEGORY_PRINTER = "printer"
REPORT_CATEGORY_SCANNER = "scanner"
REPORT_CATEGORY_MFU = "mfu"
REPORT_CATEGORY_COPIER = "copier"
REPORT_CATEGORY_OTHER = "other"
REPORT_CATEGORY_NOT_INCLUDED = "not_included"

ALLOWED_REPORT_CATEGORIES = {
    REPORT_CATEGORY_DESKTOP_PC,
    REPORT_CATEGORY_LAPTOP,
    REPORT_CATEGORY_TABLET,
    REPORT_CATEGORY_TERMINAL,
    REPORT_CATEGORY_INFO_TERMINAL,
    REPORT_CATEGORY_PROJECTOR,
    REPORT_CATEGORY_INTERACTIVE_BOARD,
    REPORT_CATEGORY_PRINTER,
    REPORT_CATEGORY_SCANNER,
    REPORT_CATEGORY_MFU,
    REPORT_CATEGORY_COPIER,
    REPORT_CATEGORY_OTHER,
    REPORT_CATEGORY_NOT_INCLUDED,
}

OWNERSHIP_TYPE_OWN = "own"
OWNERSHIP_TYPE_RENT = "rent"
OWNERSHIP_TYPE_USE = "use"
OWNERSHIP_TYPE_OTHER = "other"

ALLOWED_OWNERSHIP_TYPES = {
    OWNERSHIP_TYPE_OWN,
    OWNERSHIP_TYPE_RENT,
    OWNERSHIP_TYPE_USE,
    OWNERSHIP_TYPE_OTHER,
}
